### ISSUE TITLE
Mudar banco de SQLite para Postgres

### ISSUE THREAD

**Issue by andrearaujo-Daitan** [ivanfcfilho/ecommerce_site#1]
O banco do sqlite3 é zerado toda hora que o serviço dorme. Precisamos de persistencia no banco, creio que psql é a melhor opção.

**Comment by andrearaujo-Daitan** [comment]
https://devcenter.heroku.com/articles/heroku-postgresql

@velloso vc que tem mais manha com o heroku já, consegue fazer isso de colocar o addon lá? Pode me passar o acesso lá tb? Nao tenho. :)

**Comment by velloso** [comment]
@andrearaujo-Daitan para de dar acesso preciso do seu email do heroku, cria uma conta se vc n tiver.
Eu coloquei o addon, mas o banco ainda esta vazio, não tenho tempo para configura-lo hoje, posso ver isso amanhã.
